services:
  ddns:
    image: favonia/cloudflare-ddns:${DDNS_TAG:-1}
    container_name: brownie-the-archer-ddns
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:?err}
      - DOMAINS=${DOMAIN:?err}
      - PROXIED=${PROXIED:-true}
      - IP6_PROVIDER=none

  www:
    image: ghcr.io/forrestab/brownie-the-archer:${WWW_TAG:?err}
    container_name: brownie-the-archer
    restart: always

networks:
  default:
    name: brownie-the-archer
    external: true
